src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Mappers;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
    /// <summary>
    /// Клиенты
    /// </summary>
    [ApiController]
    [Route("api/v1/[controller]")]
    public class CustomersController
        : ControllerBase
    {
        private readonly IRepository<Customer> _customerRepository;
        private readonly IRepository<Preference> _preferenceRepository;

        public CustomersController(IRepository<Customer> customerRepository, 
            IRepository<Preference> preferenceRepository)
        {
            _customerRepository = customerRepository;
            _preferenceRepository = preferenceRepository;
        }
        
        /// <summary>
        /// Получить список клиентов
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<List<CustomerShortResponse>>> GetCustomersAsync()
        {
            var customers =  await _customerRepository.GetAllAsync();

            var response = customers.Select(x => new CustomerShortResponse()
            {
                Id = x.Id,
                Email = x.Email,
                FirstName = x.FirstName,
                LastName = x.LastName
            }).ToList();

            return Ok(response);
        }
        
        /// <summary>
        /// Получить клиента по id
        /// </summary>
        /// <param name="id">Id клиента, например <example>a6c8c6b1-4349-45b0-ab31-244740aaf0f0</example></param>
        /// <returns></returns>
        [HttpGet("{id:guid}")]
        public async Task<ActionResult<CustomerResponse>> GetCustomerAsync(Guid id)
        {
            var customer =  await _customerRepository.GetByIdAsync(id);

            var response = new CustomerResponse(customer);

            return Ok(response);
        }
        
        /// <summary>
        /// Создать нового клиента
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult<CustomerResponse>> CreateCustomerAsync(CreateOrEditCustomerRequest request)
        {
            //Получаем предпочтения из бд и сохраняем большой объект
            var preferences = await _preferenceRepository
                .GetRangeByIdsAsync(request.PreferenceIds);

            Customer customer = CustomerMapper.MapFromModel(request, preferences);
            
            await _customerRepository.AddAsync(customer);

            return CreatedAtAction(nameof(GetCustomerAsync), new {id = customer.Id}, customer.Id);
        }
        
        /// <summary>
        /// Обновить клиента
        /// </summary>
        /// <param name="id">Id клиента, например <example>a6c8c6b1-4349-45b0-ab31-244740aaf0f0</example></param>
        /// <param name="request">Данные запроса></param>
        [HttpPut("{id:guid}")]
        public async Task<IActionResult> EditCustomersAsync(Guid id, CreateOrEditCustomerRequest request)
        {
            var customer = await _customerRepository.GetByIdAsync(id);
            
            if (customer == null)
                return NotFound();
            
            var preferences = await _preferenceRepository.GetRangeByIdsAsync(request.PreferenceIds);
            
            CustomerMapper.MapFromModel(request, preferences, customer);

            await _customerRepository.UpdateAsync(customer);

            return NoContent();
        }
        
        /// <summary>
        /// Удалить клиента
        /// </summary>
        /// <param name="id">Id клиента, например <example>a6c8c6b1-4349-45b0-ab31-244740aaf0f0</example></param>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> DeleteCustomerAsync(Guid id)
        {
            var customer = await _customerRepository.GetByIdAsync(id);
            
            if (customer == null)
                return NotFound();

            await _customerRepository.DeleteAsync(customer);

            return NoContent();
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/PreferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
    /// <summary>
    /// Предпочтения клиентов
    /// </summary>
    [ApiController]
    [Route("api/v1/[controller]")]
    public class PreferencesController
        : ControllerBase
    {
        private readonly IRepository<Preference> _preferencesRepository;

        public PreferencesController(IRepository<Preference> preferencesRepository)
        {
            _preferencesRepository = preferencesRepository;
        }
        
        /// <summary>
        /// Получить список предпочтений
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<List<PreferenceResponse>>> GetPreferencesAsync()
        {
            var preferences = await _preferencesRepository.GetAllAsync();

            var response = preferences.Select(x => new PreferenceResponse()
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            return Ok(response);
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/PromocodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Mappers;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;
using Mapster;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Logic;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
    /// <summary>
    /// Промокоды
    /// </summary>
    [ApiController]
    [Route("api/v1/[controller]")]
    public class PromocodesController
        : ControllerBase
    {
        private readonly IRepository<PromoCode> _promoCodesRepository;
        private readonly IPromoCodesToCustomerGiver _promoCodesToCustomerGiver;

        public PromocodesController(IRepository<PromoCode> promoCodesRepository, 
            IRepository<Preference> preferencesRepository, IRepository<Customer> customersRepository,
            IPromoCodesToCustomerGiver promoCodesToCustomerGiver)
        {
            _promoCodesRepository = promoCodesRepository;
            _promoCodesToCustomerGiver = promoCodesToCustomerGiver;
        }
        
        /// <summary>
        /// Получить все промокоды
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult<List<PromoCodeShortResponse>>> GetPromocodesAsync()
        {
            var promocodes = await _promoCodesRepository.GetAllAsync();

            var response = promocodes.Select(x => new PromoCodeShortResponse()
            {
                Id = x.Id,
                Code = x.Code,
                BeginDate = x.BeginDate.ToString("yyyy-MM-dd"),
                EndDate = x.EndDate.ToString("yyyy-MM-dd"),
                PartnerId = x.PartnerId,
                ServiceInfo = x.ServiceInfo
            }).ToList();

            return Ok(response);
        }
        
        /// <summary>
        /// Создать промокод и выдать его клиентам с указанным предпочтением
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> GivePromoCodesToCustomersWithPreferenceAsync(GivePromoCodeRequest request) {
            try {
                await _promoCodesToCustomerGiver.GivePromoCodesToCustomersWithPreferenceAsync(
                    request.Adapt<GivePromoCodeCommand>());

                return CreatedAtAction(nameof(GetPromocodesAsync), new { }, null);
            }
            catch (Exception ex) {
                return BadRequest(ex);
            }
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Test.Pages {
    public class IndexModel : PageModel {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger) {
            _logger = logger;
        }

        public void OnGet() {

        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/Customer.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models.ViewModels;
using Mapster;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Mappers;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Pages
{
    public class CustomerModel : PageModel
    {
        public bool IsCreate => CustomerViewModel.Id.Equals(default);

        public string Title => (IsCreate ? "Create" : "Update") + " customer";

        public CustomerViewModel CustomerViewModel { get; set; } = new CustomerViewModel();

        public IEnumerable<PreferenceForCustomerViewModel> AllPreferenceViewModels { get; set; } = new List<PreferenceForCustomerViewModel>();

        public IEnumerable<PromoCodeForCustomerViewModel> AllPromocodeViewModels { get; set; } = new List<PromoCodeForCustomerViewModel>();

        private readonly IRepository<Customer> _customerRepository;

        private readonly IRepository<Preference> _preferenceRepository;

        private readonly IRepository<PromoCode> _promocodeRepository;

        public const string returnPage = "CustomerList";

        public CustomerModel(IRepository<Customer> customerRepository,
            IRepository<Preference> preferenceRepository,
            IRepository<PromoCode> promocodeRepository) 
        {
            _customerRepository = customerRepository;
            _preferenceRepository = preferenceRepository;
            _promocodeRepository = promocodeRepository;
        }

        public async Task OnGetCreate() {
            AllPreferenceViewModels = (await _preferenceRepository.GetAllAsync()).Select(x => x.Adapt<PreferenceForCustomerViewModel>());
            AllPromocodeViewModels = (await _promocodeRepository.GetAllAsync()).Select(x => x.Adapt<PromoCodeForCustomerViewModel>());
        }

        public async Task OnGetUpdate(Guid id) {
            var customeEntity =  await _customerRepository.GetByIdAsync(id);
            CustomerViewModel = customeEntity.Adapt<CustomerViewModel>();

            if (CustomerViewModel.Preferences != null) {
                var preferenceIds = customeEntity.Preferences.Select(x => x.PreferenceId).ToList();
                AllPreferenceViewModels = (await _preferenceRepository.GetAllAsync()).Select(x => {
                    var pref = x.Adapt<PreferenceForCustomerViewModel>();
                    pref.IsSelected = preferenceIds.Contains(x.Id);
                    return pref;
                });
            }
            else {
                AllPreferenceViewModels = (await _preferenceRepository.GetAllAsync()).Select(x => x.Adapt<PreferenceForCustomerViewModel>());
            }

            if (CustomerViewModel.PromoCodes != null) {
                var promocodeIds = customeEntity.PromoCodes.Select(x => x.PromoCodeId).ToList();
                AllPromocodeViewModels = (await _promocodeRepository.GetAllAsync()).Select(x => {
                    var promocode = x.Adapt<PromoCodeForCustomerViewModel>();
                    promocode.IsSelected = promocodeIds.Contains(x.Id);
                    return promocode;
                });
            }
            else {
                AllPromocodeViewModels = (await _promocodeRepository.GetAllAsync()).Select(x => x.Adapt<PromoCodeForCustomerViewModel>());
            }
        }

        public async Task<ActionResult> OnPostCreate(CustomerViewModel customerViewModel) {

            var customerEntity = CustomerMapper.MapFromViewModel(customerViewModel);
            await _customerRepository.AddAsync(customerEntity);
            return RedirectToPage(returnPage);
        }

        public async Task<ActionResult> OnPostUpdate(CustomerViewModel customerViewModel) {
            var customerEntity = CustomerMapper.MapFromViewModel(customerViewModel);
            await _customerRepository.UpdateAsync(customerEntity);
            return RedirectToPage(returnPage);
        }

        public async Task<ActionResult> OnPostDelete(Guid id) {
            await _customerRepository.DeleteAsync(id);
            return RedirectToPage(returnPage);
        }
    }


}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/CustomerDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Pages
{
    public class CustomerDetailsModel : PageModel
    {
        public Customer Customer { get; set; } = new Customer();

        public IEnumerable<Preference> Preferences { get; set; } = new List<Preference>();

        public IEnumerable<PromoCode> Promocodes { get; set; } = new List<PromoCode>();

        private readonly IRepository<Customer> _customerRepository;

        private readonly IRepository<Preference> _preferenceRepository;

        private readonly IRepository<PromoCode> _promocodeRepository;

        public CustomerDetailsModel(
            IRepository<Customer> customerRepository,
            IRepository<Preference> preferenceRepository,
            IRepository<PromoCode> promocodeRepository
            ) 
        {
            _customerRepository = customerRepository;
            _preferenceRepository = preferenceRepository;
            _promocodeRepository = promocodeRepository;
        }

        public async Task OnGet(Guid id) {
            Customer = await _customerRepository.GetByIdAsync(id);

            if (Customer.Preferences != null) {
                var preferenceIds = Customer.Preferences.Select(x => x.PreferenceId).ToList();
                Preferences = await _preferenceRepository.GetRangeByIdsAsync(preferenceIds);
            }

            if (Customer.PromoCodes != null) {
                var promocodeIds = Customer.PromoCodes.Select(x => x.PromoCodeId).ToList();
                Promocodes = await _promocodeRepository.GetRangeByIdsAsync(promocodeIds);
            } 
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/CustomerList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Pages
{
    public class CustomerListModel : PageModel {

        private readonly IRepository<Customer> _customerRepository;

        public IEnumerable<Customer> Customers { get; set; }

        public CustomerListModel(IRepository<Customer> customerRepository) {
            _customerRepository = customerRepository;
        }

        public async Task OnGetAsync() {
            Customers = await _customerRepository.GetAllAsync();
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/PreferenceDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Abstractions.Repositories;
using Otus.Teaching.Pcf.GivingToCustomer.Core.Domain;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models.ViewModels;
using Mapster;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Pages
{
    public class PreferenceDetailsModel : PageModel
    {
        public PreferenceViewModel PreferenceViewModel { get; set; }

        private readonly IRepository<Preference> _preferenceRepository;

        public const string returnUrl = "PreferenceList";

        public PreferenceDetailsModel(IRepository<Preference> preferenceRepository) {
            _preferenceRepository = preferenceRepository;
        }

        public async Task OnGet(Guid id) {
            PreferenceViewModel = (await _preferenceRepository.GetByIdAsync(id)).Adapt<PreferenceViewModel>();
        }
    }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/Admin.cshtml
@page
@{
    ViewData["Title"] = "Admin page";
}

<div class="text-center">

    <h1>What would you like to destroy?</h1>

    <div>
        <a asp-page="PreferenceList"><h1>Preferences</h1></a>
        <a asp-page="CustomerList"><h1>Customers</h1></a>
        <a asp-page="PromocodeList"><h1>Promocodes</h1></a>
    </div>

</div>

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/CustomerDetails.cshtml
@page "/Admin/CustomerDetails"
@model CustomerDetailsModel
@{
    ViewData["Title"] = "Customer details";
}

<h1>Customer details</h1>
<hr />

<div class="form-group">
    <label asp-for="@Model.Customer.FirstName">First Name:</label>
    <input class="form-control" type="text" asp-for="@Model.Customer.FirstName" readonly>
</div>
<div class="form-group">
    <label asp-for="@Model.Customer.LastName">Last Name:</label>
    <input class="form-control" type="text" asp-for="@Model.Customer.LastName" readonly>
</div>
<div class="form-group">
    <label asp-for="@Model.Customer.Email">Email:</label>
    <input class="form-control" type="text" asp-for="@Model.Customer.Email" readonly>
</div>
<div class="form-group">
    <label asp-for="@Model.Customer.Preferences">Preferences:</label>
    <select multiple class="form-control" readonly>
        @foreach (var pref in @Model.Preferences) {
            <option>@pref.Name</option>
        }
    </select>
</div>
<div class="form-group">
    <label asp-for="@Model.Customer.PromoCodes">Promocodes:</label>
    <select multiple class="form-control" readonly>
        @foreach (var p in @Model.Promocodes) {
            <option>@p.Code</option>
        }
    </select>
</div>

<div>
    <a class="btn btn-sm btn-primary" asp-page="Customer" asp-page-handler="Update" asp-route-id="@Model.Customer.Id">Edit</a> |
    <form class="m-0 p-0 d-inline" asp-page="Customer" asp-page-handler="Delete" method="post">
        <input type="hidden" name="Id"
               value="@Model.Customer.Id" />
        <button type="submit" class="btn btn-sm btn-danger">
            Delete
        </button>
    </form>
</div>

<div>
    <a asp-page="CustomerList">Back to List</a>
</div>

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/CustomerList.cshtml
@page "/Admin/CustomerList"
@model CustomerListModel

<h1 class="text-center m-2 p-2">Customers management page!</h1>

<a class="btn btn-sm btn-primary m-2 p-2" asp-page="Customer" asp-page-handler="Create">Create new</a>

<div>
    <table class="table table-sm table-bordered table-striped">
        <thead>
            <tr>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var @c in Model.Customers) {
            <tr>
                <td>
                    @Html.DisplayFor(model => c.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(model => c.LastName)
                </td>
                <td>
                    @Html.DisplayFor(model => c.Email)
                </td>
                <td>
                    <a class="btn btn-sm btn-outline-primary" asp-page="Customer" asp-page-handler="Update" asp-route-id="@c.Id">Edit</a> |
                    <a class="btn btn-sm btn-outline-primary" asp-page="CustomerDetails" asp-route-id="@c.Id">Details</a> |
                    <form class="m-0 p-0 d-inline" asp-page="Customer" asp-page-handler="Delete" method="post">
                        <input type="hidden" name="Id" value="@c.Id" />
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>            
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-page="Admin">Back to admin page</a>
</div>

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/Preference.cshtml
@page "/Admin/Preference"
@model PreferenceModel
@{
}

@{
    ViewData["Title"] = @Model.Title;
}

<h1>@Model.Title</h1>
<hr />

<form method="post">
    <div class="form-group">
        <input type="hidden" asp-for="PreferenceViewModel.Id" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PreferenceViewModel.Name" class="control-label">Name:</label>
        <input asp-for="PreferenceViewModel.Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-page="PreferenceList">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/PreferenceDetails.cshtml
@page "/Admin/PreferenceDetails"
@model PreferenceDetailsModel
@{
    ViewData["Title"] = "Preference details";
}


<h1>Preference details</h1>
<hr />

<div class="form-group">
    <label asp-for="@Model.PreferenceViewModel.Name">Name:</label>
    <input class="form-control" type="text" asp-for="@Model.PreferenceViewModel.Name" readonly>
</div>

<div>
    <a class="btn btn-sm btn-primary" asp-page="Preference" asp-page-handler="Update" asp-route-id="@Model.PreferenceViewModel.Id">Edit</a> |
    <form class="m-0 p-0 d-inline" asp-page="Preference" asp-page-handler="Delete" method="post">
        <input type="hidden" name="Id"
               value="@Model.PreferenceViewModel.Id" />
        <button type="submit" class="btn btn-sm btn-danger">
            Delete
        </button>
    </form>
</div>

<div>
    <a asp-page="PreferenceList">Back to List</a>
</div>

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/PreferenceList.cshtml
@page "/Admin/PreferenceList"
@model PreferenceListModel

<h1 class="text-center m-2 p-2">Preferences management page!</h1>

<a class="btn btn-sm btn-primary m-2 p-2" asp-page="Preference" asp-page-handler="Create">Create new</a>

<div>
    <table class="table table-sm table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var @p in Model.PreferenceViewModels) {
            <tr>
                <td>
                    @Html.DisplayFor(model => p.Name)
                </td>
                <td>
                    <a class="btn btn-sm btn-outline-primary" asp-page="Preference" asp-page-handler="Update" asp-route-id="@p.Id">Edit</a> |
                    <a class="btn btn-sm btn-outline-primary" asp-page="PreferenceDetails" asp-route-id="@p.Id">Details</a> |
                    <form class="m-0 p-0 d-inline" asp-page="Preference" asp-page-handler="Delete" method="post">
                        <input type="hidden" name="Id" value="@p.Id" />
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>            
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-page="Admin">Back to admin page</a>
</div>

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Pages/PromocodeList.cshtml
@page "/Admin/PromocodeList"
@model PromocodeListModel

<h1 class="text-center m-2 p-2">Promocodes management page!</h1>

<a class="btn btn-sm btn-primary m-2 p-2" asp-page="Promocode" asp-page-handler="Create">Create new</a>

<div>
    <table class="table table-sm table-bordered table-striped">
        <thead>
            <tr>
                <th>Code</th>
                <th>Service info</th>
                <th>Begin date</th>
                <th>End date</th>
                <th>Preference</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var @p in Model.PromocodeViewModels) {
            <tr>
                <td>
                    @Html.DisplayFor(model => p.Code)
                </td>
                <td>
                    @Html.DisplayFor(model => p.ServiceInfo)
                </td>
                <td>
                    @Html.DisplayFor(model => p.BeginDate)
                </td>
                <td>
                    @Html.DisplayFor(model => p.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(model => p.PreferenceName)
                </td>
                <td>
                    <a class="btn btn-sm btn-outline-primary" asp-page="Promocode" asp-page-handler="Update" asp-route-id="@p.Id">Edit</a> |
                    <a class="btn btn-sm btn-outline-primary" asp-page="PromocodeDetails" asp-route-id="@p.Id">Details</a> |
                    <form class="m-0 p-0 d-inline" asp-page="Promocode" asp-page-handler="Delete" method="post">
                        <input type="hidden" name="Id" value="@p.Id" />
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-page="Admin">Back to admin page</a>
</div>